FROM python:3.11-slim
WORKDIR /elastik
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install -r requirements.txt
EXPOSE 3004
ENV PYTHONUNBUFFERED=1
CMD ["python", "server.py"]